# Generated by Django 6.0.5 on 2026-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
